import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

export default function AboutPage() {
  return (
    <div className="container py-10">
      <h1 className="text-3xl font-bold mb-2">About OnlySq Chat</h1>
      <p className="text-gray-500 mb-8">Learn more about our AI chat platform</p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-10">
        <Card>
          <CardHeader>
            <CardTitle>Our Platform</CardTitle>
            <CardDescription>Powered by OnlySq API</CardDescription>
          </CardHeader>
          <CardContent>
            <p>
              OnlySq Chat provides a user-friendly interface to interact with various AI models through the OnlySq API.
              Our platform allows you to have natural conversations with state-of-the-art language models.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Available Models</CardTitle>
            <CardDescription>Multiple AI models to choose from</CardDescription>
          </CardHeader>
          <CardContent>
            <p>
              We offer access to several leading AI models including GPT-3.5, GPT-4, and Claude 3. Each model has its
              own strengths and capabilities, allowing you to choose the best option for your specific needs.
            </p>
          </CardContent>
        </Card>
      </div>

      <h2 className="text-2xl font-bold mb-4">How It Works</h2>
      <div className="space-y-4 mb-10">
        <div className="flex gap-4 items-start">
          <div className="bg-primary/10 text-primary rounded-full p-2 w-10 h-10 flex items-center justify-center font-bold">
            1
          </div>
          <div>
            <h3 className="text-lg font-medium">Select a Model</h3>
            <p className="text-gray-500">Choose from our collection of AI models based on your needs</p>
          </div>
        </div>

        <div className="flex gap-4 items-start">
          <div className="bg-primary/10 text-primary rounded-full p-2 w-10 h-10 flex items-center justify-center font-bold">
            2
          </div>
          <div>
            <h3 className="text-lg font-medium">Start a Conversation</h3>
            <p className="text-gray-500">Type your message and send it to the AI</p>
          </div>
        </div>

        <div className="flex gap-4 items-start">
          <div className="bg-primary/10 text-primary rounded-full p-2 w-10 h-10 flex items-center justify-center font-bold">
            3
          </div>
          <div>
            <h3 className="text-lg font-medium">Receive AI Response</h3>
            <p className="text-gray-500">Get a thoughtful response generated by the selected AI model</p>
          </div>
        </div>
      </div>

      <div className="text-center text-gray-500 text-sm mt-20">
        <p>© {new Date().getFullYear()} OnlySq Chat. All rights reserved.</p>
        <p className="mt-1">Powered by the OnlySq API</p>
      </div>
    </div>
  )
}
